## FIFA ANALYTICS

In [38]:
# Installing SQL module in the notebook
#!pip install ipython-sql

In [39]:
import sqlalchemy
sqlalchemy.__version__

'1.3.22'

In [40]:
#Loading the SQL module
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [41]:
# connect to a SQLite database
%sql sqlite://

In [42]:
# importing the database

%sql sqlite:///D://fifaDB.db

### PART A: Let's Get a General Overview of the database
    
The database is named **fifaDB** and has only one table called **soccer**.

In [43]:
#show the table structure

%sql PRAGMA table_info('soccer');

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[(0, 'id', 'VARCHAR', 0, None, 1),
 (1, 'name', 'STRING', 0, None, 0),
 (2, 'full_name', 'STRING', 0, None, 0),
 (3, 'birth_date', 'DATE', 0, None, 0),
 (4, 'age', 'INTEGER', 0, None, 0),
 (5, 'height_cm', 'DECIMAL', 0, None, 0),
 (6, 'weight_kgs', 'DECIMAL', 0, None, 0),
 (7, 'positions', 'VARCHAR', 0, None, 0),
 (8, 'nationality', 'STRING', 0, None, 0),
 (9, 'overall_rating', 'INTEGER', 0, None, 0),
 (10, 'potential', 'INTEGER', 0, None, 0),
 (11, 'value_euro', 'INTEGER', 0, None, 0),
 (12, 'wage_euro', 'INTEGER', 0, None, 0),
 (13, 'preferred_foot', 'STRING', 0, None, 0),
 (14, 'international_reputation(1-5)', 'INTEGER', 0, None, 0),
 (15, 'weak_foot(1-5)', 'INTEGER', 0, None, 0),
 (16, 'skill_moves(1-5)', 'INTEGER', 0, None, 0),
 (17, 'work_rate', 'VARCHAR', 0, None, 0),
 (18, 'body_type', 'STRING', 0, None, 0),
 (19, 'release_clause_euro', 'INTEGER', 0, None, 0),
 (20, 'club_team', 'VARCHAR', 0, None, 0),
 (21, 'club_rating', 'INTEGER', 0, None, 0),
 (22, 'club_position', 'STRING', 0, None, 0),
 (23, 'club_jersey_number', 'INTEGER', 0, None, 0),
 (24, 'club_join_date', 'DATE', 0, None, 0),
 (25, 'contract_end_year', 'DATE', 0, None, 0),
 (26, 'national_team', 'VARCHAR', 0, None, 0),
 (27, 'national_rating', 'INTEGER', 0, None, 0),
 (28, 'national_team_position', 'STRING', 0, None, 0),
 (29, 'national_jersey_number', 'INTEGER', 0, None, 0),
 (30, 'crossing', 'INTEGER', 0, None, 0),
 (31, 'finishing', 'INTEGER', 0, None, 0),
 (32, 'heading_accuracy', 'INTEGER', 0, None, 0),
 (33, 'short_passing', 'INTEGER', 0, None, 0),
 (34, 'volleys', 'INTEGER', 0, None, 0),
 (35, 'dribbling', 'INTEGER', 0, None, 0),
 (36, 'curve', 'INTEGER', 0, None, 0),
 (37, 'freekick_accuracy', 'INTEGER', 0, None, 0),
 (38, 'long_passing', 'INTEGER', 0, None, 0),
 (39, 'ball_control', 'INTEGER', 0, None, 0),
 (40, 'acceleration', 'INTEGER', 0, None, 0),
 (41, 'sprint_speed', 'INTEGER', 0, None, 0),
 (42, 'agility\n', 'INTEGER', 0, None, 0),
 (43, 'jumping', 'INTEGER', 0, None, 0),
 (44, 'stamina', 'INTEGER', 0, None, 0),
 (45, 'penalties', 'INTEGER', 0, None, 0),
 (46, 'composure', 'INTEGER', 0, None, 0),
 (47, 'tags', 'VARCHAR', 0, None, 0)]

In [44]:
# check the first 10 rows of the table

%sql SELECT * FROM soccer LIMIT 10;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[('158023', 'L. Messi', 'Lionel AndrÃ©s Messi Cuccittini', '24/06/1987', 31, 170.18, 72.1, 'CF,RW,ST', 'Argentina', 94, 94, 110500000, 565000, 'Left', 5, 4, 4, 'Medium/ Low', 'Messi', 226500000, 'FC Barcelona', 86, 'RW', 10, '01/07/2004', 2021, 'Argentina', 82, 'RF', 10, 86, 95, 70, 92, 86, 97, 93, 94, 89, 96, 91, 86, 93, 68, 72, 75, 96, '#Dribbler,#Distance Shooter,#Crosser,#FK Specialist,#Acrobat,#Clinical Finisher,#Complete Forward'),
 ('190460', 'C. Eriksen', 'Christian  Dannemann Eriksen', '14/02/1992', 27, 154.94, 76.2, 'CAM,RM,CM', 'Denmark', 88, 89, 69500000, 205000, 'Right', 3, 5, 4, 'High/ Medium', 'Lean', 133800000, 'Tottenham Hotspur', 83, 'LCM', 23, '30/08/2013', 2020, 'Denmark', 78, 'CAM', 10, 88, 81, 52, 91, 80, 84, 86, 87, 89, 91, 76, 73, 80, 50, 92, 67, 88, '#PlaymakerÂ\xa0 ,#Crosser,#FK Specialist,#Complete Midfielder'),
 ('195864', 'P. Pogba', 'Paul Pogba', '15/03/1993', 25, 190.5, 83.9, 'CM,CAM', 'France', 88, 91, 73000000, 255000, 'Right', 4, 4, 5, 'High/ Medium', 'Normal', 144200000, 'Manchester United', 82, 'LCM', 6, '09/08/2016', 2021, 'France', 84, 'RDM', 6, 80, 75, 75, 86, 85, 87, 85, 82, 90, 90, 71, 79, 76, 83, 88, 82, 87, '#Dribbler,#PlaymakerÂ\xa0 ,#Strength,#Complete Midfielder'),
 ('198219', 'L. Insigne', 'Lorenzo Insigne', '04/06/1991', 27, 162.56, 59, 'LW,ST', 'Italy', 88, 88, 62000000, 165000, 'Right', 3, 4, 4, 'High/ Medium', 'Normal', 105400000, 'Napoli', 82, 'LS', 24, '01/07/2010', 2022, 'Italy', 83, 'LW', 10, 86, 77, 56, 85, 74, 90, 87, 77, 78, 93, 94, 86, 94, 53, 75, 61, 83, '#Speedster,#Dribbler,#Crosser,#Acrobat'),
 ('201024', 'K. Koulibaly', 'Kalidou Koulibaly', '20/06/1991', 27, 187.96, 88.9, 'CB', 'Senegal', 88, 91, 60000000, 135000, 'Right', 3, 3, 2, 'High/ High', 'Normal', 106500000, 'Napoli', 82, 'LCB', 26, '01/07/2014', 2021, None, None, None, None, 30, 22, 83, 68, 14, 69, 28, 28, 60, 63, 70, 75, 50, 81, 75, 33, 80, '#TacklingÂ\xa0,#TacticianÂ\xa0,#Strength,#Complete Defender'),
 ('203376', 'V. van Dijk', 'Virgil van Dijk', '08/07/1991', 27, 193.04, 92.1, 'CB', 'Netherlands', 88, 90, 59500000, 215000, 'Right', 3, 3, 2, 'Medium/ Medium', 'Normal', 114500000, 'Liverpool', 83, 'LCB', 4, '01/01/2018', 2023, 'Netherlands', 81, 'LCB', 4, 53, 52, 83, 79, 45, 70, 60, 70, 81, 76, 74, 77, 61, 88, 75, 62, 87, '#TacticianÂ\xa0,#Strength'),
 ('231747', 'K. MbappÃ©', 'Kylian MbappÃ©', '20/12/1998', 20, 152.4, 73, 'RW,ST,RM', 'France', 88, 95, 81000000, 100000, 'Right', 3, 4, 5, 'High/ Medium', 'Lean', 166100000, 'Paris Saint-Germain', 84, 'LS', 7, '01/07/2018', 2022, 'France', 84, 'RM', 10, 77, 88, 77, 82, 78, 90, 77, 63, 73, 91, 96, 96, 92, 75, 83, 70, 86, '#Speedster,#Dribbler,#Acrobat'),
 ('153079', 'S. AgÃ¼ero', 'Sergio Leonel AgÃ¼ero del Castillo', '02/06/1988', 30, 172.72, 69.9, 'ST', 'Argentina', 89, 89, 64500000, 300000, 'Right', 4, 4, 4, 'High/ Medium', 'Stocky', 119300000, 'Manchester City', 85, 'ST', 10, '28/07/2011', 2021, 'Argentina', 82, 'SUB', 11, 70, 93, 77, 81, 85, 89, 82, 73, 64, 89, 88, 80, 86, 81, 76, 83, 90, '#Dribbler,#Acrobat,#Clinical Finisher,#Complete Forward'),
 ('167495', 'M. Neuer', 'Manuel Neuer', '27/03/1986', 32, 193.04, 92.1, 'GK', 'Germany', 89, 89, 38000000, 130000, 'Right', 5, 4, 1, 'Medium/ Medium', 'Normal', 62700000, 'FC Bayern MÃ¼nchen', 85, 'GK', 1, '01/07/2011', 2021, 'Germany', 85, 'GK', 1, 15, 13, 25, 55, 11, 30, 14, 11, 59, 46, 54, 60, 51, 77, 43, 47, 70, None),
 ('179813', 'E. Cavani', 'Edinson Roberto Cavani GÃ³mez', '14/02/1987', 32, 185.42, 77.1, 'ST', 'Uruguay', 89, 89, 60000000, 200000, 'Right', 4, 4, 3, 'High/ High', 'Lean', 111000000, 'Paris Saint-Germain', 84, 'RS', 9, '16/07/2013', 2020, 'Uruguay', 81, 'LS', 21, 70, 89, 89, 78, 90, 80, 77, 76, 52, 82, 75, 76, 77, 88, 92, 85, 82, '#Engine')]

In [45]:
# Let's get the next 20 rows after the first 10 rows

%sql SELECT * FROM soccer LIMIT 20 OFFSET 10;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[('189511', 'Sergio Busquets', 'Sergio Busquets i Burgos', '16/07/1988', 30, 187.96, 76.2, 'CDM,CM', 'Spain', 89, 89, 51500000, 315000, 'Right', 4, 3, 3, 'Medium/ Medium', 'Lean', 105600000, 'FC Barcelona', 86, 'CDM', 5, '01/09/2008', 2023, 'Spain', 85, 'CDM', 5, 62, 67, 68, 89, 44, 80, 66, 68, 82, 88, 50, 52, 66, 66, 86, 60, 93, '#PlaymakerÂ\xa0 ,#TacticianÂ\xa0'),
 ('192119', 'T. Courtois', 'Thibaut Courtois', '11/05/1992', 26, 198.12, 96.2, 'GK', 'Belgium', 89, 90, 53500000, 240000, 'Left', 4, 2, 1, 'Medium/ Medium', 'Courtois', 113700000, 'Real Madrid', 86, 'GK', 25, '09/08/2018', 2024, 'Belgium', 85, 'GK', 1, 14, 14, 13, 33, 12, 13, 19, 20, 35, 23, 46, 52, 61, 68, 38, 27, 66, None),
 ('192448', 'M. ter Stegen', 'Marc-AndrÃ© ter Stegen', '30/04/1992', 26, 187.96, 84.8, 'GK', 'Germany', 89, 92, 58000000, 240000, 'Right', 3, 4, 1, 'Medium/ Medium', 'Normal', 123300000, 'FC Barcelona', 86, 'GK', 1, '01/07/2014', 2022, 'Germany', 85, 'SUB', 22, 18, 14, 11, 42, 14, 17, 18, 12, 47, 18, 38, 50, 37, 79, 35, 25, 70, None),
 ('194765', 'A. Griezmann', 'Antoine Griezmann', '21/03/1991', 27, 175.26, 73, 'CF,ST', 'France', 89, 90, 78000000, 145000, 'Left', 4, 3, 4, 'High/ High', 'Lean', 165800000, 'AtlÃ©tico Madrid', 84, 'RS', 7, '28/07/2014', 2023, 'France', 84, 'CAM', 7, 82, 89, 84, 84, 87, 87, 86, 84, 78, 90, 88, 85, 90, 90, 86, 83, 89, '#Dribbler,#Engine,#Acrobat,#Clinical Finisher,#Complete Forward'),
 ('209331', 'M. Salah', 'Mohamed  Salah Ghaly', '15/06/1992', 26, 175.26, 71.2, 'RW,ST', 'Egypt', 89, 90, 78500000, 265000, 'Left', 3, 3, 4, 'High/ Medium', 'PLAYER_BODY_TYPE_25', 151100000, 'Liverpool', 83, 'ST', 11, '01/07/2017', 2023, 'Egypt', 73, 'RM', 10, 78, 90, 59, 83, 76, 89, 83, 60, 74, 88, 94, 91, 91, 68, 84, 75, 91, '#Speedster,#Dribbler,#Acrobat,#Clinical Finisher,#Complete Forward'),
 ('211110', 'P. Dybala', 'Paulo Bruno Exequiel Dybala', '15/11/1993', 25, 152.4, 74.8, 'CAM,RW', 'Argentina', 89, 94, 89000000, 205000, 'Left', 3, 3, 4, 'Medium/ Medium', 'Normal', 153500000, 'Juventus', 85, 'RW', 10, '01/07/2015', 2022, 'Argentina', 82, 'LF', 21, 82, 84, 68, 87, 88, 92, 88, 88, 75, 92, 87, 83, 91, 75, 80, 86, 84, '#Dribbler,#PlaymakerÂ\xa0 ,#FK Specialist,#Acrobat,#Complete Midfielder'),
 ('232363', 'M. Å\xa0kriniar', 'Milan Å\xa0kriniar', '11/02/1995', 24, 187.96, 79.8, 'CB', 'Slovakia', 86, 93, 53500000, 89000, 'Right', 1, 4, 2, 'Medium/ High', 'Normal', 101700000, 'Inter', 82, 'LCB', 37, '07/07/2017', 2022, None, None, None, None, 40, 42, 82, 73, 40, 59, 34, 30, 69, 67, 70, 73, 48, 78, 77, 56, 81, '#TacticianÂ\xa0'),
 ('135507', 'Fernandinho', 'Fernando Luiz Rosa', '04/05/1985', 33, 152.4, 67.1, 'CDM', 'Brazil', 87, 87, 20500000, 200000, 'Right', 3, 4, 3, 'Medium/ High', 'Lean', 37900000, 'Manchester City', 85, 'CDM', 25, '01/07/2013', 2020, None, None, None, None, 68, 69, 66, 85, 74, 77, 70, 72, 83, 82, 68, 67, 72, 78, 84, 61, 79, '#TacticianÂ\xa0'),
 ('167664', 'G. HiguaÃ\xadn', 'Gonzalo Gerardo HiguaÃ\xadn', '10/12/1987', 31, 185.42, 88.9, 'ST', 'Argentina', 87, 87, 48500000, 205000, 'Right', 4, 4, 3, 'High/ Medium', 'Normal', None, 'Chelsea', 83, 'ST', 9, None, 'Jun 30, 2019', None, None, None, None, 68, 91, 79, 74, 88, 83, 74, 62, 59, 84, 70, 72, 75, 79, 70, 70, 86, '#Clinical Finisher'),
 ('168651', 'I. RakitiÄ‡', 'Ivan RakitiÄ‡', '10/03/1988', 30, 182.88, 78, 'CM,CDM', 'Croatia', 87, 87, 46500000, 260000, 'Right', 4, 4, 3, 'Medium/ High', 'Lean', 95300000, 'FC Barcelona', 86, 'LCM', 4, '01/07/2014', 2021, None, None, None, None, 84, 79, 59, 87, 84, 82, 88, 82, 90, 85, 66, 62, 73, 39, 83, 82, 86, '#PlaymakerÂ\xa0 '),
 ('172871', 'J. Vertonghen', 'Jan Vertonghen', '24/04/1987', 31, 187.96, 86.2, 'CB', 'Belgium', 87, 87, 34000000, 155000, 'Left', 3, 3, 3, 'High/ High', 'Normal', 62900000, 'Tottenham Hotspur', 83, 'LCB', 5, '01/07/2012', 2020, 'Belgium', 85, 'LCB', 5, 72, 56, 80, 79, 52, 71, 63, 73, 74, 77, 61, 65, 61, 85, 75, 66, 83, '#TacklingÂ\xa0,#TacticianÂ\xa0'),
 ('175943', 'D. Mertens', 'Dries Mertens', '06/05/1987', 31, 170.18, 60.8, 'CF,ST', 'Belgium', 87, 87, 45000000, 135000, 'Right', 3, 4, 4, 'High/ Low', 'Normal', 76500000, 'Napoli', 82, 'SUB', 14, '01/07/2013', 2020, 'Belgium', 85, 'RF', 14, 77, 86, 35, 82, 70, 91, 82, 79, 74, 89, 93, 85, 94, 60, 75, 79, 81, '#Dribbler,#Acrobat,#Clinical Finisher,#Complete Forward'),
 ('176676', 'Marcelo', 'Marcelo Vieira da Silva JÃºnior', '12/05/1988', 30, 175.26, 79.8, 'LB', 'Brazil', 87, 87, 36500000, 240000, 'Left', 4, 4, 5, 'High/ Low', 'Normal', 74800000, 'Real Madrid', 86, 'SUB', 12, '01/01/2007', 2022, None, None, None, None, 90, 73, 75, 84, 61, 90, 85, 67, 78, 92, 83, 82, 86, 76, 89, 59, 86, '#Dribbler,#Crosser,#Acrobat'),
 ('184087', 'T. Alderweireld', 'Toby Alderweireld', '02/03/1989', 30, 185.42, 81.2, 'CB', 'Belgium', 87, 88, 44000000, 165000, 'Right', 3, 3, 2, 'Medium/ Medium', 'Normal', 84700000, 'Tottenham Hotspur', 83, 'RCB', 4, '08/07/2015', 2020, 'Belgium', 85, 'RCB', 2, 64, 45, 82, 79, 38, 62, 63, 69, 85, 75, 61, 67, 60, 84, 76, 58, 84, '#TacklingÂ\xa0,#TacticianÂ\xa0'),
 ('189332', 'Jordi Alba', 'Jordi Alba Ramos', '21/03/1989', 29, 170.18, 68, 'LB', 'Spain', 87, 87, 38000000, 250000, 'Left', 3, 3, 3, 'High/ Medium', 'Normal', 77900000, 'FC Barcelona', 86, 'LB', 18, '01/07/2012', 2024, 'Spain', 85, 'LB', 18, 87, 73, 70, 84, 60, 80, 80, 63, 74, 84, 93, 93, 90, 81, 91, 59, 82, '#Speedster,#Crosser,#Acrobat'),
 ('189509', 'Thiago', 'Thiago AlcÃ¢ntara do Nascimento', '11/04/1991', 27, 175.26, 69.9, 'CM,CAM,CDM', 'Spain', 87, 87, 51500000, 140000, 'Right', 3, 3, 5, 'Medium/ Medium', 'Normal', 85000000, 'FC Bayern MÃ¼nchen', 85, 'LDM', 6, '14/07/2013', 2021, 'Spain', 85, 'SUB', 19, 72, 69, 54, 90, 90, 90, 85, 77, 87, 90, 78, 69, 90, 75, 75, 75, 85, '#Dribbler,#PlaymakerÂ\xa0 ,#Acrobat,#Complete Midfielder'),
 ('192387', 'C. Immobile', 'Ciro Immobile', '20/02/1990', 29, 185.42, 84.8, 'ST', 'Italy', 87, 87, 52000000, 115000, 'Right', 3, 4, 3, 'High/ Medium', 'Normal', 88400000, 'Lazio', 80, 'ST', 17, '27/07/2016', 2023, 'Italy', 83, 'ST', 17, 55, 90, 81, 74, 87, 83, 70, 51, 49, 83, 78, 85, 77, 77, 80, 78, 81, '#Clinical Finisher'),
 ('193041', 'K. Navas', 'Keylor Navas', '15/12/1986', 32, 185.42, 79.8, 'GK', 'Costa Rica', 87, 87, 30500000, 195000, 'Right', 3, 3, 1, 'Medium/ Medium', 'Normal', 62500000, 'Real Madrid', 86, 'SUB', 1, '03/08/2014', 2020, None, None, None, None, 11, 15, 11, 30, 11, 16, 11, 15, 37, 19, 54, 53, 60, 74, 39, 25, 67, None),
 ('197781', 'Isco', 'Francisco RomÃ¡n AlarcÃ³n SuÃ¡rez', '21/04/1992', 26, 175.26, 78.9, 'CAM,CM,LW', 'Spain', 87, 90, 62500000, 260000, 'Right', 3, 3, 4, 'High/ Medium', 'Normal', 132800000, 'Real Madrid', 86, 'SUB', 22, '03/07/2013', 2022, 'Spain', 85, 'LW', 22, 75, 79, 55, 86, 65, 94, 88, 76, 81, 95, 75, 69, 87, 64, 70, 76, 86, '#Dribbler,#PlaymakerÂ\xa0 ,#Complete Midfielder'),
 ('198710', 'J. RodrÃ\xadguez', 'James David RodrÃ\xadguez Rubio', '12/07/1991', 27, 154.94, 74.8, 'CAM,CM,RM', 'Colombia', 87, 88, 59000000, 260000, 'Left', 4, 3, 4, 'Medium/ Medium', 'Normal', None, 'FC Bayern MÃ¼nchen', 85, 'CAM', 11, None, 'Jun 30, 2019', 'Colombia', 79, 'LAM', 10, 90, 83, 62, 89, 90, 85, 89, 86, 83, 90, 73, 67, 83, 54, 70, 81, 87, '#PlaymakerÂ\xa0 ,#Distance Shooter,#Crosser,#FK Specialist,#Complete Midfielder')]

#### 1. How many distinct players are in this table?

In [46]:
%%sql

SELECT COUNT(*) FROM soccer;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[(17954,)]

#### 2. How many distinct nationalities are there?

In [47]:
%%sql

SELECT COUNT (DISTINCT nationality) 
AS 'Number of Nationalities' 
FROM soccer;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[(160,)]

#### 3. How many players come from each nationality?

Top 10 nationalities based on the number of palyers

In [48]:
%%sql

SELECT nationality, COUNT(nationality)
FROM soccer
GROUP BY nationality
ORDER BY COUNT(nationality)
DESC
LIMIT 10;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[('England', 1658),
 ('Germany', 1199),
 ('Spain', 1070),
 ('France', 925),
 ('Argentina', 904),
 ('Brazil', 832),
 ('Italy', 655),
 ('Colombia', 624),
 ('Japan', 466),
 ('Netherlands', 441)]

The last 10 nationalities based on the number of players

In [49]:
%%sql

SELECT nationality, COUNT(nationality)
FROM soccer
GROUP BY nationality
ORDER BY COUNT(nationality)
ASC
LIMIT 10;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[('Andorra', 1),
 ('Barbados', 1),
 ('Ethiopia', 1),
 ('Guam', 1),
 ('Indonesia', 1),
 ('Kuwait', 1),
 ('Malta', 1),
 ('New Caledonia', 1),
 ('Nicaragua', 1),
 ('Oman', 1)]

#### 4. How many distinct club_teams are there? And How many players come form each club?

Number of club teams

In [50]:
%%sql

SELECT COUNT (DISTINCT club_team) 
AS 'Number of Club Teams' 
FROM soccer;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[(687,)]

Top ten club teams based on the number of players

In [51]:
%%sql

SELECT club_team, COUNT(club_team)
FROM soccer
GROUP BY club_team
ORDER BY COUNT(club_team)
DESC
LIMIT 10;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[('Wolverhampton Wanderers', 33),
 ('Valencia CF', 33),
 ('Southampton', 33),
 ('Sevilla FC', 33),
 ('Real Madrid', 33),
 ('Rayo Vallecano', 33),
 ('RC Celta', 33),
 ('Manchester United', 33),
 ('Manchester City', 33),
 ('Huddersfield Town', 33)]

Bottom 10 club teams based on the number of players

In [52]:
%%sql

SELECT club_team, COUNT(club_team)
FROM soccer
GROUP BY club_team
ORDER BY COUNT(club_team)
ASC
LIMIT 10;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[(None, 0),
 ('Italy', 1),
 ('Poland', 1),
 ('Republic of Ireland', 1),
 ('Belgium', 2),
 ('Czech Republic', 2),
 ('Greece', 2),
 ('Sweden', 2),
 ('Wales', 2),
 ('Canada', 4)]

#### 5. Find out the rank of club_teams based on the average overall_rating of players whose overall_rating is greater than 80

In [53]:
%%sql

SELECT club_team, AVG(overall_rating)
FROM soccer
WHERE overall_rating > 80
GROUP BY club_team
ORDER BY AVG(overall_rating)
DESC;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[('Real Madrid', 86.5),
 ('Manchester City', 85.6470588235294),
 ('Juventus', 85.52941176470588),
 ('FC Barcelona', 85.47368421052632),
 ('Paris Saint-Germain', 85.35714285714286),
 ('FC Bayern MÃ¼nchen', 85.17647058823529),
 ('Tottenham Hotspur', 85.08333333333333),
 ('LA Galaxy', 85.0),
 ('Chelsea', 84.53846153846153),
 ('Olympique Lyonnais', 84.33333333333333),
 ('Liverpool', 84.23076923076923),
 ('AtlÃ©tico Madrid', 84.17647058823529),
 ('RC Celta', 84.0),
 ('Inter', 84.0),
 ('Guangzhou Evergrande Taobao FC', 84.0),
 ('BeÅŸiktaÅŸ JK', 84.0),
 ('AS Saint-Ã‰tienne', 84.0),
 ('Manchester United', 83.91666666666667),
 ('Napoli', 83.9090909090909),
 ('Portugal', 83.75),
 ('Lazio', 83.42857142857143),
 ('FC Porto', 83.2),
 ('Arsenal', 83.08333333333333),
 ('Vissel Kobe', 83.0),
 ('Real Sociedad', 83.0),
 ('Medipol BaÅŸakÅŸehir FK', 83.0),
 ('Hertha BSC', 83.0),
 ('1. FC KÃ¶ln', 83.0),
 ('Borussia Dortmund', 82.77777777777777),
 ('GrÃªmio', 82.66666666666667),
 ('Valencia CF', 82.57142857142857),
 ('Roma', 82.55555555555556),
 ('Olympique de Marseille', 82.5),
 ('Belgium', 82.5),
 ('AtlÃ©tico Mineiro', 82.5),
 ('Atalanta', 82.5),
 ('Ajax', 82.5),
 ('AS Monaco', 82.5),
 ('RB Leipzig', 82.4),
 ('West Ham United', 82.33333333333333),
 ('Sevilla FC', 82.28571428571429),
 ('Everton', 82.25),
 ('Real Betis', 82.14285714285714),
 ('Milan', 82.125),
 ('Wolverhampton Wanderers', 82.0),
 ('VfL Wolfsburg', 82.0),
 ('Uruguay', 82.0),
 ('Torino', 82.0),
 ('TSG 1899 Hoffenheim', 82.0),
 ('Sporting CP', 82.0),
 ('Shanghai SIPG FC', 82.0),
 ('Shakhtar Donetsk', 82.0),
 ('Sassuolo', 82.0),
 ('Sampdoria', 82.0),
 ('SV Werder Bremen', 82.0),
 ('SPAL', 82.0),
 ('PSV', 82.0),
 ('PFC CSKA Moscow', 82.0),
 ('Montpellier HSC', 82.0),
 ('Italy', 82.0),
 ('Dalian YiFang FC', 82.0),
 ('Crystal Palace', 82.0),
 ('Cruzeiro', 82.0),
 ('Atlanta United', 82.0),
 ('Al Nassr', 82.0),
 ('Borussia MÃ¶nchengladbach', 81.83333333333333),
 ('SL Benfica', 81.8),
 ('Leicester City', 81.8),
 ('Bayer 04 Leverkusen', 81.7),
 ('FC Schalke 04', 81.66666666666667),
 ('Beijing Sinobo Guoan FC', 81.66666666666667),
 ('Villarreal CF', 81.5),
 ('Mexico', 81.5),
 ('Lokomotiv Moscow', 81.33333333333333),
 ('Eintracht Frankfurt', 81.33333333333333),
 ('Athletic Club de Bilbao', 81.33333333333333),
 ('Watford', 81.0),
 ('Orlando City SC', 81.0),
 ('Newcastle United', 81.0),
 ('Los Angeles FC', 81.0),
 ('Levante UD', 81.0),
 ('Girona FC', 81.0),
 ('Galatasaray SK', 81.0),
 ('Fluminense', 81.0),
 ('Al Hilal', 81.0)]

#### 6. Find out overall_rating, wage and value of players in Manchester United ranked based on their overall_rating

In [54]:
%%sql

SELECT name, overall_rating, wage_euro, value_euro
FROM soccer
WHERE club_team = 'Manchester United'
ORDER BY overall_rating DESC, value_euro;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[('De Gea', 91, 260000, 72000000),
 ('P. Pogba', 88, 255000, 73000000),
 ('R. Lukaku', 86, 215000, 55000000),
 ('N. MatiÄ‡', 84, 165000, 24000000),
 ('A. SÃ¡nchez', 84, 195000, 30500000),
 ('A. Martial', 84, 165000, 42500000),
 ('M. Rashford', 83, 130000, 37500000),
 ('Juan Mata', 82, 155000, 21000000),
 ('J. Lingard', 82, 150000, 26500000),
 ('Ander Herrera', 81, 140000, 17500000),
 ('E. Bailly', 81, 105000, 19500000),
 ('V. LindelÃ¶f', 81, 105000, 21000000),
 ('S. Romero', 80, 91000, 9000000),
 ('C. Smalling', 80, 120000, 12000000),
 ('L. Shaw', 80, 96000, 16500000),
 ('Fred', 80, 120000, 18000000),
 ('A. Young', 79, 110000, 7000000),
 ('A. Valencia', 79, 110000, 7000000),
 ('M. Rojo', 79, 115000, 10000000),
 ('P. Jones', 79, 110000, 12000000),
 ('Andreas Pereira', 77, 86000, 11500000),
 ('M. Darmian', 76, 88000, 6000000),
 ('L. Grant', 74, 39000, 1300000),
 ('Diogo Dalot', 73, 29000, 6000000),
 ('S. McTominay', 71, 43000, 3800000),
 ('A. Gomes', 67, 15000, 1500000),
 ('T. Chong', 66, 15000, 1300000),
 ('M. Greenwood', 66, 11000, 1300000),
 ('C. Gribbin', 65, 11000, 1000000),
 ('E. Laird', 64, 5000, 800000),
 ('J. Bohui', 64, 11000, 975000),
 ('J. Garner', 63, 7000, 650000),
 ("L. O'Connor", 62, 6000, 525000)]

#### 7. Find out overall_rating, wage and value of players in Arsenal ranked based on their overall_rating

In [55]:
%%sql

SELECT name, overall_rating, wage_euro, value_euro
FROM soccer
WHERE club_team = 'Arsenal'
ORDER BY overall_rating DESC, value_euro;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[('P. Aubameyang', 88, 265000, 59000000),
 ('M. Ã–zil', 85, 175000, 37500000),
 ('A. Lacazette', 85, 180000, 45000000),
 ('Sokratis', 83, 130000, 19000000),
 ('B. Leno', 83, 105000, 22500000),
 ('P. ÄŒech', 82, 60000, 3000000),
 ('L. Koscielny', 82, 115000, 12500000),
 ('H. Mkhitaryan', 82, 135000, 21500000),
 ('S. Mustafi', 82, 115000, 22500000),
 ('A. Ramsey', 82, 130000, 23000000),
 ('L. Torreira', 82, 98000, 25000000),
 ('G. Xhaka', 81, 115000, 22000000),
 ('Nacho Monreal', 80, 99000, 8000000),
 ('HÃ©ctor BellerÃ\xadn', 80, 85000, 16500000),
 ('S. KolaÅ¡inac', 79, 89000, 13000000),
 ('Denis SuÃ¡rez', 79, 120000, 16000000),
 ('A. Iwobi', 78, 81000, 14000000),
 ('S. Lichtsteiner', 77, 79000, 2500000),
 ('M. Elneny', 77, 76000, 9000000),
 ('D. Welbeck', 77, 95000, 9500000),
 ('R. Holding', 76, 64000, 9500000),
 ('M. Guendouzi', 72, 28000, 6000000),
 ('A. Maitland-Niles', 71, 38000, 4200000),
 ('C. Jenkinson', 69, 34000, 1000000),
 ('Pleguezuelo', 68, 21000, 1200000),
 ('K. Mavropanos', 68, 21000, 1800000),
 ('E. Nketiah', 66, 13000, 1400000),
 ('G. Zelalem', 65, 15000, 875000),
 ('B. Saka', 65, 9000, 1200000),
 ('C. Bramall', 63, 12000, 425000),
 ('J. Willock', 63, 7000, 750000),
 ('Z. Medley', 60, 5000, 375000),
 ('D. Iliev', 57, 7000, 110000)]

#### 8. What are the club_team, overall_rating, club_position and dribling score of players whose prefered foot is left

In [57]:
%%sql

SELECT name, club_team, overall_rating, club_position, dribbling
FROM soccer
WHERE preferred_foot = 'Left'
ORDER BY overall_rating DESC
LIMIT 25;

   sqlite://
 * sqlite:///D://fifaDB.db
Done.

[('L. Messi', 'FC Barcelona', 94, 'RW', 97),
 ('G. Chiellini', 'Juventus', 90, 'LCB', 58),
 ('David Silva', 'Manchester City', 90, 'LCM', 89),
 ('T. Courtois', 'Real Madrid', 89, 'GK', 13),
 ('A. Griezmann', 'AtlÃ©tico Madrid', 89, 'RS', 87),
 ('M. Salah', 'Liverpool', 89, 'ST', 89),
 ('P. Dybala', 'Juventus', 89, 'RW', 92),
 ('H. Lloris', 'Tottenham Hotspur', 88, 'GK', 10),
 ('G. Bale', 'Real Madrid', 88, 'SUB', 87),
 ('J. Vertonghen', 'Tottenham Hotspur', 87, 'LCB', 71),
 ('Marcelo', 'Real Madrid', 87, 'SUB', 90),
 ('Jordi Alba', 'FC Barcelona', 87, 'LB', 80),
 ('J. RodrÃ\xadguez', 'FC Bayern MÃ¼nchen', 87, 'CAM', 85),
 ('S. Umtiti', 'FC Barcelona', 87, 'LCB', 69),
 ('Alex Sandro', 'Juventus', 86, 'LB', 80),
 ('R. Lukaku', 'Manchester United', 86, 'SUB', 78),
 ('Ederson', 'Manchester City', 86, 'GK', 23),
 ('Bernardo Silva', 'Manchester City', 86, 'RW', 92),
 ('L. SanÃ©', 'Manchester City', 86, 'SUB', 88),
 ('Filipe LuÃ\xads', 'AtlÃ©tico Madrid', 85, 'LB', 77),
 ('B. Matuidi', 'Juventus', 85, 'LCM', 78),
 ('M. Ã–zil', 'Arsenal', 85, 'CAM', 84),
 ('A. Di MarÃ\xada', 'Paris Saint-Germain', 85, 'RAM', 86),
 ('Douglas Costa', 'Juventus', 85, 'SUB', 92),
 ('A. Lopes', 'Olympique Lyonnais', 85, 'GK', 15)]